export const DEMO_TABLES = {
  data: [
    {
      id: "demo-1",
      name: "customers",
      fullyQualifiedName: "sample_data.ecommerce_db.shopify.customers",
      description: "Customer master data including PII, contact info, and loyalty metrics",
      columns: [
        { name: "customer_id", dataType: "INT", description: "Unique customer identifier", tags: [] },
        { name: "first_name", dataType: "VARCHAR", description: "Customer first name", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "last_name", dataType: "VARCHAR", description: "Customer last name", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "email", dataType: "VARCHAR", description: "Customer email address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "phone_number", dataType: "VARCHAR", description: "Customer phone number", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "date_of_birth", dataType: "DATE", description: "Customer date of birth", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "ip_address", dataType: "VARCHAR", description: "Last login IP address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "ssn", dataType: "VARCHAR", description: "Social security number", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "credit_card_number", dataType: "VARCHAR", description: "Payment card number", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "billing_address", dataType: "VARCHAR", description: "Billing street address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "city", dataType: "VARCHAR", description: "Billing city", tags: [{ tagFQN: "PII.NonSensitive" }] },
        { name: "country", dataType: "VARCHAR", description: "Billing country", tags: [{ tagFQN: "PII.NonSensitive" }] },
        { name: "total_orders", dataType: "INT", description: "Lifetime order count", tags: [] },
        { name: "loyalty_points", dataType: "INT", description: "Current loyalty points balance", tags: [] },
        { name: "created_at", dataType: "TIMESTAMP", description: "Account creation timestamp", tags: [] },
      ],
      tags: [],
    },
    {
      id: "demo-2",
      name: "orders",
      fullyQualifiedName: "sample_data.ecommerce_db.shopify.orders",
      description: "Order transactions with shipping details and payment information",
      columns: [
        { name: "order_id", dataType: "INT", description: "Unique order identifier", tags: [] },
        { name: "customer_id", dataType: "INT", description: "Reference to customer", tags: [] },
        { name: "order_date", dataType: "TIMESTAMP", description: "When the order was placed", tags: [] },
        { name: "shipping_address", dataType: "VARCHAR", description: "Delivery street address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "shipping_city", dataType: "VARCHAR", description: "Delivery city", tags: [{ tagFQN: "PII.NonSensitive" }] },
        { name: "shipping_zip", dataType: "VARCHAR", description: "Delivery postal code", tags: [{ tagFQN: "PII.NonSensitive" }] },
        { name: "total_amount", dataType: "DECIMAL", description: "Order total in USD", tags: [] },
        { name: "payment_method", dataType: "VARCHAR", description: "Payment method used", tags: [] },
        { name: "status", dataType: "VARCHAR", description: "Order status", tags: [] },
      ],
      tags: [],
    },
    {
      id: "demo-3",
      name: "employees",
      fullyQualifiedName: "sample_data.ecommerce_db.shopify.employees",
      description: "Employee records including payroll, tax, and department information",
      columns: [
        { name: "employee_id", dataType: "INT", description: "Employee identifier", tags: [] },
        { name: "full_name", dataType: "VARCHAR", description: "Employee full name", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "work_email", dataType: "VARCHAR", description: "Corporate email address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "personal_email", dataType: "VARCHAR", description: "Personal email address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "phone", dataType: "VARCHAR", description: "Contact phone number", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "salary", dataType: "DECIMAL", description: "Annual salary in USD", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "bank_account", dataType: "VARCHAR", description: "Bank account number for payroll", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "tax_id", dataType: "VARCHAR", description: "Tax identification number", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "department", dataType: "VARCHAR", description: "Department name", tags: [] },
        { name: "hire_date", dataType: "DATE", description: "Date of hire", tags: [] },
        { name: "is_active", dataType: "BOOLEAN", description: "Currently employed flag", tags: [] },
      ],
      tags: [],
    },
    {
      id: "demo-4",
      name: "products",
      fullyQualifiedName: "sample_data.ecommerce_db.shopify.products",
      description: "Product catalog with pricing and inventory data",
      columns: [
        { name: "product_id", dataType: "INT", description: "Unique product identifier", tags: [] },
        { name: "product_name", dataType: "VARCHAR", description: "Product display name", tags: [] },
        { name: "category", dataType: "VARCHAR", description: "Product category", tags: [] },
        { name: "price", dataType: "DECIMAL", description: "Product price in USD", tags: [] },
        { name: "sku", dataType: "VARCHAR", description: "Stock keeping unit code", tags: [] },
        { name: "inventory_count", dataType: "INT", description: "Current inventory quantity", tags: [] },
        { name: "supplier_contact_email", dataType: "VARCHAR", description: "Supplier contact email address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "created_at", dataType: "TIMESTAMP", description: "Product listing date", tags: [] },
      ],
      tags: [],
    },
    {
      id: "demo-5",
      name: "payments",
      fullyQualifiedName: "sample_data.ecommerce_db.shopify.payments",
      description: "Payment transactions with card and billing details",
      columns: [
        { name: "payment_id", dataType: "INT", description: "Unique payment identifier", tags: [] },
        { name: "order_id", dataType: "INT", description: "Associated order", tags: [] },
        { name: "card_number", dataType: "VARCHAR", description: "Credit card number used", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "card_holder_name", dataType: "VARCHAR", description: "Name on the credit card", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "billing_email", dataType: "VARCHAR", description: "Billing email address", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "billing_phone", dataType: "VARCHAR", description: "Billing phone number", tags: [{ tagFQN: "PII.Sensitive" }] },
        { name: "amount", dataType: "DECIMAL", description: "Payment amount", tags: [] },
        { name: "payment_status", dataType: "VARCHAR", description: "Payment status", tags: [] },
        { name: "processed_at", dataType: "TIMESTAMP", description: "Payment processing timestamp", tags: [] },
      ],
      tags: [],
    },
  ],
  paging: { total: 5 },
};

export const DEMO_HEALTH = {
  score: 72,
  metrics: {
    totalTables: 5,
    descriptionCoverage: 100,
    tagCoverage: 55,
    tableLevelTagCoverage: 100,
    totalColumns: 48,
    taggedColumns: 26,
    tablesWithDescription: 5,
    tablesWithTags: 5,
  },
};

export const DEMO_SCAN_RESULTS: Record<string, { column: string; classification: string; confidence: number; reason: string }[]> = {
  "sample_data.ecommerce_db.shopify.customers": [
    { column: "customer_id", classification: "NotPII", confidence: 0.98, reason: "Internal identifier with no personal information" },
    { column: "first_name", classification: "PII.Sensitive", confidence: 0.97, reason: "Directly identifies a person" },
    { column: "last_name", classification: "PII.Sensitive", confidence: 0.97, reason: "Directly identifies a person" },
    { column: "email", classification: "PII.Sensitive", confidence: 0.99, reason: "Email directly identifies an individual" },
    { column: "phone_number", classification: "PII.Sensitive", confidence: 0.98, reason: "Phone number directly identifies a person" },
    { column: "date_of_birth", classification: "PII.Sensitive", confidence: 0.96, reason: "Date of birth is a direct personal identifier" },
    { column: "ip_address", classification: "PII.Sensitive", confidence: 0.92, reason: "IP address can identify a user's location and device" },
    { column: "ssn", classification: "PII.Sensitive", confidence: 0.99, reason: "Social security number is a critical personal identifier" },
    { column: "credit_card_number", classification: "PII.Sensitive", confidence: 0.99, reason: "Payment card number is highly sensitive financial PII" },
    { column: "billing_address", classification: "PII.Sensitive", confidence: 0.95, reason: "Physical address identifies a person's residence" },
    { column: "city", classification: "PII.NonSensitive", confidence: 0.88, reason: "City alone doesn't identify an individual" },
    { column: "country", classification: "PII.NonSensitive", confidence: 0.90, reason: "Country alone doesn't identify an individual" },
    { column: "total_orders", classification: "NotPII", confidence: 0.97, reason: "Aggregate metric with no personal data" },
    { column: "loyalty_points", classification: "NotPII", confidence: 0.96, reason: "Points balance is not personally identifying" },
    { column: "created_at", classification: "NotPII", confidence: 0.95, reason: "Timestamp of account creation, not personal" },
  ],
  "sample_data.ecommerce_db.shopify.payments": [
    { column: "payment_id", classification: "NotPII", confidence: 0.98, reason: "Internal identifier" },
    { column: "order_id", classification: "NotPII", confidence: 0.97, reason: "Internal reference key" },
    { column: "card_number", classification: "PII.Sensitive", confidence: 0.99, reason: "Credit card number is highly sensitive financial PII" },
    { column: "card_holder_name", classification: "PII.Sensitive", confidence: 0.98, reason: "Name on card directly identifies a person" },
    { column: "billing_email", classification: "PII.Sensitive", confidence: 0.98, reason: "Email directly identifies an individual" },
    { column: "billing_phone", classification: "PII.Sensitive", confidence: 0.97, reason: "Phone number directly identifies a person" },
    { column: "amount", classification: "NotPII", confidence: 0.95, reason: "Transaction amount is not personally identifying" },
    { column: "payment_status", classification: "NotPII", confidence: 0.96, reason: "Status field with no personal data" },
    { column: "processed_at", classification: "NotPII", confidence: 0.95, reason: "Processing timestamp, not personal" },
  ],
};